#!/bin/sh

PKGVER=$(node -e "console.log(require('./package.json').version)")
ARCHIVE=minichrome-$PKGVER.tar.gz

cd build
tar -czvf ../pkg/pkgbuild/aur/$ARCHIVE minichrome-linux-x64
cd ../pkg/pkgbuild/aur
MD5SUM=$(md5sum $ARCHIVE | cut -d ' ' -f 1)
sed "s/%PKGVER%/$PKGVER/;s/%ARCHIVE%/$ARCHIVE/;s/%MD5SUM%/$MD5SUM/" ../PKGBUILD > PKGBUILD
makepkg --printsrcinfo > .SRCINFO
