#!/bin/sh

PKGVER=$(node -e "console.log(require('./package.json').version)")
ARCHIVE=minichrome-$PKGVER.tar.gz

mkdir -p build
cp package.json build
minify index.js > build/index.js
minify ui.js > build/ui.js
minify page.js > build/page.js
cd build
electron-packager .
tar -czvf $ARCHIVE minichrome-linux-x64
rm *.js package.json
